package com.contravenciones.tr.persistence;
// Generated 30/12/2017 12:47:12 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CivDivipos generated by hbm2java
 */
public class CivDivipos  implements java.io.Serializable {


     private BigDecimal divId;
     private BigDecimal depId;
     private BigDecimal munId;
     private BigDecimal pobId;
     private BigDecimal divCodigo;
     private BigDecimal paiId;

    public CivDivipos() {
    }

	
    public CivDivipos(BigDecimal divId) {
        this.divId = divId;
    }
    public CivDivipos(BigDecimal divId, BigDecimal depId, BigDecimal munId, BigDecimal pobId, BigDecimal divCodigo, BigDecimal paiId) {
       this.divId = divId;
       this.depId = depId;
       this.munId = munId;
       this.pobId = pobId;
       this.divCodigo = divCodigo;
       this.paiId = paiId;
    }
   
    public BigDecimal getDivId() {
        return this.divId;
    }
    
    public void setDivId(BigDecimal divId) {
        this.divId = divId;
    }
    public BigDecimal getDepId() {
        return this.depId;
    }
    
    public void setDepId(BigDecimal depId) {
        this.depId = depId;
    }
    public BigDecimal getMunId() {
        return this.munId;
    }
    
    public void setMunId(BigDecimal munId) {
        this.munId = munId;
    }
    public BigDecimal getPobId() {
        return this.pobId;
    }
    
    public void setPobId(BigDecimal pobId) {
        this.pobId = pobId;
    }
    public BigDecimal getDivCodigo() {
        return this.divCodigo;
    }
    
    public void setDivCodigo(BigDecimal divCodigo) {
        this.divCodigo = divCodigo;
    }
    public BigDecimal getPaiId() {
        return this.paiId;
    }
    
    public void setPaiId(BigDecimal paiId) {
        this.paiId = paiId;
    }




}


