package com.contravenciones.tr.persistence;
// Generated 30/12/2017 12:47:12 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivDirecciones generated by hbm2java
 */
public class CivDirecciones  implements java.io.Serializable {


     private BigDecimal dirId;
     private CivPersonas civPersonas;
     private String dirDescripcion;
     private String dirTelefono;
     private BigDecimal dirEstado;
     private Date dirFechainicial;
     private Date dirFechafinal;
     private Date dirFechaproceso;
     private BigDecimal divId;

    public CivDirecciones() {
    }

	
    public CivDirecciones(BigDecimal dirId) {
        this.dirId = dirId;
    }
    public CivDirecciones(BigDecimal dirId, CivPersonas civPersonas, String dirDescripcion, String dirTelefono, BigDecimal dirEstado, Date dirFechainicial, Date dirFechafinal, Date dirFechaproceso, BigDecimal divId) {
       this.dirId = dirId;
       this.civPersonas = civPersonas;
       this.dirDescripcion = dirDescripcion;
       this.dirTelefono = dirTelefono;
       this.dirEstado = dirEstado;
       this.dirFechainicial = dirFechainicial;
       this.dirFechafinal = dirFechafinal;
       this.dirFechaproceso = dirFechaproceso;
       this.divId = divId;
    }
   
    public BigDecimal getDirId() {
        return this.dirId;
    }
    
    public void setDirId(BigDecimal dirId) {
        this.dirId = dirId;
    }
    public CivPersonas getCivPersonas() {
        return this.civPersonas;
    }
    
    public void setCivPersonas(CivPersonas civPersonas) {
        this.civPersonas = civPersonas;
    }
    public String getDirDescripcion() {
        return this.dirDescripcion;
    }
    
    public void setDirDescripcion(String dirDescripcion) {
        this.dirDescripcion = dirDescripcion;
    }
    public String getDirTelefono() {
        return this.dirTelefono;
    }
    
    public void setDirTelefono(String dirTelefono) {
        this.dirTelefono = dirTelefono;
    }
    public BigDecimal getDirEstado() {
        return this.dirEstado;
    }
    
    public void setDirEstado(BigDecimal dirEstado) {
        this.dirEstado = dirEstado;
    }
    public Date getDirFechainicial() {
        return this.dirFechainicial;
    }
    
    public void setDirFechainicial(Date dirFechainicial) {
        this.dirFechainicial = dirFechainicial;
    }
    public Date getDirFechafinal() {
        return this.dirFechafinal;
    }
    
    public void setDirFechafinal(Date dirFechafinal) {
        this.dirFechafinal = dirFechafinal;
    }
    public Date getDirFechaproceso() {
        return this.dirFechaproceso;
    }
    
    public void setDirFechaproceso(Date dirFechaproceso) {
        this.dirFechaproceso = dirFechaproceso;
    }
    public BigDecimal getDivId() {
        return this.divId;
    }
    
    public void setDivId(BigDecimal divId) {
        this.divId = divId;
    }




}


