package com.contravenciones.tr.persistence;
// Generated 30/12/2017 12:47:12 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CivDepartamentos generated by hbm2java
 */
public class CivDepartamentos  implements java.io.Serializable {


     private BigDecimal depId;
     private String depNombre;
     private String depCodigoarea;
     private BigDecimal depCoddepartamento;
     private BigDecimal paiId;

    public CivDepartamentos() {
    }

	
    public CivDepartamentos(BigDecimal depId) {
        this.depId = depId;
    }
    public CivDepartamentos(BigDecimal depId, String depNombre, String depCodigoarea, BigDecimal depCoddepartamento, BigDecimal paiId) {
       this.depId = depId;
       this.depNombre = depNombre;
       this.depCodigoarea = depCodigoarea;
       this.depCoddepartamento = depCoddepartamento;
       this.paiId = paiId;
    }
   
    public BigDecimal getDepId() {
        return this.depId;
    }
    
    public void setDepId(BigDecimal depId) {
        this.depId = depId;
    }
    public String getDepNombre() {
        return this.depNombre;
    }
    
    public void setDepNombre(String depNombre) {
        this.depNombre = depNombre;
    }
    public String getDepCodigoarea() {
        return this.depCodigoarea;
    }
    
    public void setDepCodigoarea(String depCodigoarea) {
        this.depCodigoarea = depCodigoarea;
    }
    public BigDecimal getDepCoddepartamento() {
        return this.depCoddepartamento;
    }
    
    public void setDepCoddepartamento(BigDecimal depCoddepartamento) {
        this.depCoddepartamento = depCoddepartamento;
    }
    public BigDecimal getPaiId() {
        return this.paiId;
    }
    
    public void setPaiId(BigDecimal paiId) {
        this.paiId = paiId;
    }




}


