package com.contravenciones.tr.persistence;
// Generated 30/12/2017 12:47:12 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivGrupos generated by hbm2java
 */
public class CivGrupos  implements java.io.Serializable {


     private BigDecimal gruId;
     private String gruNombre;
     private Date fechaInicial;
     private Date fechaFinal;
     private BigDecimal usuId;
     private Set civParametroses = new HashSet(0);

    public CivGrupos() {
    }

	
    public CivGrupos(BigDecimal gruId) {
        this.gruId = gruId;
    }
    public CivGrupos(BigDecimal gruId, String gruNombre, Date fechaInicial, Date fechaFinal, BigDecimal usuId, Set civParametroses) {
       this.gruId = gruId;
       this.gruNombre = gruNombre;
       this.fechaInicial = fechaInicial;
       this.fechaFinal = fechaFinal;
       this.usuId = usuId;
       this.civParametroses = civParametroses;
    }
   
    public BigDecimal getGruId() {
        return this.gruId;
    }
    
    public void setGruId(BigDecimal gruId) {
        this.gruId = gruId;
    }
    public String getGruNombre() {
        return this.gruNombre;
    }
    
    public void setGruNombre(String gruNombre) {
        this.gruNombre = gruNombre;
    }
    public Date getFechaInicial() {
        return this.fechaInicial;
    }
    
    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }
    public BigDecimal getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(BigDecimal usuId) {
        this.usuId = usuId;
    }
    public Set getCivParametroses() {
        return this.civParametroses;
    }
    
    public void setCivParametroses(Set civParametroses) {
        this.civParametroses = civParametroses;
    }




}


