package com.contravenciones.tr.persistence;
// Generated 30/12/2017 12:47:12 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CivMunicipios generated by hbm2java
 */
public class CivMunicipios  implements java.io.Serializable {


     private BigDecimal munId;
     private String munNombre;
     private BigDecimal munCodmunicipio;
     private BigDecimal depId;
     private BigDecimal paiId;

    public CivMunicipios() {
    }

	
    public CivMunicipios(BigDecimal munId) {
        this.munId = munId;
    }
    public CivMunicipios(BigDecimal munId, String munNombre, BigDecimal munCodmunicipio, BigDecimal depId, BigDecimal paiId) {
       this.munId = munId;
       this.munNombre = munNombre;
       this.munCodmunicipio = munCodmunicipio;
       this.depId = depId;
       this.paiId = paiId;
    }
   
    public BigDecimal getMunId() {
        return this.munId;
    }
    
    public void setMunId(BigDecimal munId) {
        this.munId = munId;
    }
    public String getMunNombre() {
        return this.munNombre;
    }
    
    public void setMunNombre(String munNombre) {
        this.munNombre = munNombre;
    }
    public BigDecimal getMunCodmunicipio() {
        return this.munCodmunicipio;
    }
    
    public void setMunCodmunicipio(BigDecimal munCodmunicipio) {
        this.munCodmunicipio = munCodmunicipio;
    }
    public BigDecimal getDepId() {
        return this.depId;
    }
    
    public void setDepId(BigDecimal depId) {
        this.depId = depId;
    }
    public BigDecimal getPaiId() {
        return this.paiId;
    }
    
    public void setPaiId(BigDecimal paiId) {
        this.paiId = paiId;
    }




}


