package com.contravenciones.tr.persistence;
// Generated 30/12/2017 12:47:12 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivOrganismos generated by hbm2java
 */
public class CivOrganismos  implements java.io.Serializable {


     private BigDecimal orgId;
     private String orgNombre;
     private String orgTelefono;
     private String orgDireccion;
     private String orgEmail;
     private String orgNit;
     private String orgCodigo;
     private String orgNombrecorto;
     private BigDecimal orgEstado;
     private Date orgFechainicial;
     private Date orgFechafinal;
     private Date orgFechaproceso;
     private BigDecimal usuId;

    public CivOrganismos() {
    }

	
    public CivOrganismos(BigDecimal orgId) {
        this.orgId = orgId;
    }
    public CivOrganismos(BigDecimal orgId, String orgNombre, String orgTelefono, String orgDireccion, String orgEmail, String orgNit, String orgCodigo, String orgNombrecorto, BigDecimal orgEstado, Date orgFechainicial, Date orgFechafinal, Date orgFechaproceso, BigDecimal usuId) {
       this.orgId = orgId;
       this.orgNombre = orgNombre;
       this.orgTelefono = orgTelefono;
       this.orgDireccion = orgDireccion;
       this.orgEmail = orgEmail;
       this.orgNit = orgNit;
       this.orgCodigo = orgCodigo;
       this.orgNombrecorto = orgNombrecorto;
       this.orgEstado = orgEstado;
       this.orgFechainicial = orgFechainicial;
       this.orgFechafinal = orgFechafinal;
       this.orgFechaproceso = orgFechaproceso;
       this.usuId = usuId;
    }
   
    public BigDecimal getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(BigDecimal orgId) {
        this.orgId = orgId;
    }
    public String getOrgNombre() {
        return this.orgNombre;
    }
    
    public void setOrgNombre(String orgNombre) {
        this.orgNombre = orgNombre;
    }
    public String getOrgTelefono() {
        return this.orgTelefono;
    }
    
    public void setOrgTelefono(String orgTelefono) {
        this.orgTelefono = orgTelefono;
    }
    public String getOrgDireccion() {
        return this.orgDireccion;
    }
    
    public void setOrgDireccion(String orgDireccion) {
        this.orgDireccion = orgDireccion;
    }
    public String getOrgEmail() {
        return this.orgEmail;
    }
    
    public void setOrgEmail(String orgEmail) {
        this.orgEmail = orgEmail;
    }
    public String getOrgNit() {
        return this.orgNit;
    }
    
    public void setOrgNit(String orgNit) {
        this.orgNit = orgNit;
    }
    public String getOrgCodigo() {
        return this.orgCodigo;
    }
    
    public void setOrgCodigo(String orgCodigo) {
        this.orgCodigo = orgCodigo;
    }
    public String getOrgNombrecorto() {
        return this.orgNombrecorto;
    }
    
    public void setOrgNombrecorto(String orgNombrecorto) {
        this.orgNombrecorto = orgNombrecorto;
    }
    public BigDecimal getOrgEstado() {
        return this.orgEstado;
    }
    
    public void setOrgEstado(BigDecimal orgEstado) {
        this.orgEstado = orgEstado;
    }
    public Date getOrgFechainicial() {
        return this.orgFechainicial;
    }
    
    public void setOrgFechainicial(Date orgFechainicial) {
        this.orgFechainicial = orgFechainicial;
    }
    public Date getOrgFechafinal() {
        return this.orgFechafinal;
    }
    
    public void setOrgFechafinal(Date orgFechafinal) {
        this.orgFechafinal = orgFechafinal;
    }
    public Date getOrgFechaproceso() {
        return this.orgFechaproceso;
    }
    
    public void setOrgFechaproceso(Date orgFechaproceso) {
        this.orgFechaproceso = orgFechaproceso;
    }
    public BigDecimal getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(BigDecimal usuId) {
        this.usuId = usuId;
    }




}


