package com.contravenciones.tr.persistence;
// Generated 30/12/2017 12:47:12 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivSedes generated by hbm2java
 */
public class CivSedes  implements java.io.Serializable {


     private BigDecimal sedId;
     private String sedNit;
     private String sedCodigo;
     private String sedNombrecorto;
     private String sedNombre;
     private BigDecimal orgId;
     private String direccion;
     private BigDecimal usuId;
     private Date sedFechainicial;
     private Date sedFinal;
     private BigDecimal sedEstado;
     private Set civUsuarioCajases = new HashSet(0);
     private Set civUsuarioses = new HashSet(0);

    public CivSedes() {
    }

	
    public CivSedes(BigDecimal sedId) {
        this.sedId = sedId;
    }
    public CivSedes(BigDecimal sedId, String sedNit, String sedCodigo, String sedNombrecorto, String sedNombre, BigDecimal orgId, String direccion, BigDecimal usuId, Date sedFechainicial, Date sedFinal, BigDecimal sedEstado, Set civUsuarioCajases, Set civUsuarioses) {
       this.sedId = sedId;
       this.sedNit = sedNit;
       this.sedCodigo = sedCodigo;
       this.sedNombrecorto = sedNombrecorto;
       this.sedNombre = sedNombre;
       this.orgId = orgId;
       this.direccion = direccion;
       this.usuId = usuId;
       this.sedFechainicial = sedFechainicial;
       this.sedFinal = sedFinal;
       this.sedEstado = sedEstado;
       this.civUsuarioCajases = civUsuarioCajases;
       this.civUsuarioses = civUsuarioses;
    }
   
    public BigDecimal getSedId() {
        return this.sedId;
    }
    
    public void setSedId(BigDecimal sedId) {
        this.sedId = sedId;
    }
    public String getSedNit() {
        return this.sedNit;
    }
    
    public void setSedNit(String sedNit) {
        this.sedNit = sedNit;
    }
    public String getSedCodigo() {
        return this.sedCodigo;
    }
    
    public void setSedCodigo(String sedCodigo) {
        this.sedCodigo = sedCodigo;
    }
    public String getSedNombrecorto() {
        return this.sedNombrecorto;
    }
    
    public void setSedNombrecorto(String sedNombrecorto) {
        this.sedNombrecorto = sedNombrecorto;
    }
    public String getSedNombre() {
        return this.sedNombre;
    }
    
    public void setSedNombre(String sedNombre) {
        this.sedNombre = sedNombre;
    }
    public BigDecimal getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(BigDecimal orgId) {
        this.orgId = orgId;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public BigDecimal getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(BigDecimal usuId) {
        this.usuId = usuId;
    }
    public Date getSedFechainicial() {
        return this.sedFechainicial;
    }
    
    public void setSedFechainicial(Date sedFechainicial) {
        this.sedFechainicial = sedFechainicial;
    }
    public Date getSedFinal() {
        return this.sedFinal;
    }
    
    public void setSedFinal(Date sedFinal) {
        this.sedFinal = sedFinal;
    }
    public BigDecimal getSedEstado() {
        return this.sedEstado;
    }
    
    public void setSedEstado(BigDecimal sedEstado) {
        this.sedEstado = sedEstado;
    }
    public Set getCivUsuarioCajases() {
        return this.civUsuarioCajases;
    }
    
    public void setCivUsuarioCajases(Set civUsuarioCajases) {
        this.civUsuarioCajases = civUsuarioCajases;
    }
    public Set getCivUsuarioses() {
        return this.civUsuarioses;
    }
    
    public void setCivUsuarioses(Set civUsuarioses) {
        this.civUsuarioses = civUsuarioses;
    }




}


