package com.contravenciones.tr.persistence;
// Generated 30/12/2017 12:47:12 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivUsuarios generated by hbm2java
 */
public class CivUsuarios  implements java.io.Serializable {


     private BigDecimal usuId;
     private CivPersonas civPersonas;
     private CivSedes civSedes;
     private String usuNombre;
     private String usuPassword;
     private BigDecimal usuEstado;
     private Date usuFechainicial;
     private Date usuFechafinal;
     private Date usuFechaproceso;
     private BigDecimal usuUsuariorunt;
     private Set civAttemptses = new HashSet(0);
     private Set civDetalleRecUsus = new HashSet(0);
     private Set civUsuperfils = new HashSet(0);
     private Set civUspHistorias = new HashSet(0);
     private Set civPerfilrecursos = new HashSet(0);
     private Set civUsuarioCajases = new HashSet(0);

    public CivUsuarios() {
    }

	
    public CivUsuarios(BigDecimal usuId) {
        this.usuId = usuId;
    }
    public CivUsuarios(BigDecimal usuId, CivPersonas civPersonas, CivSedes civSedes, String usuNombre, String usuPassword, BigDecimal usuEstado, Date usuFechainicial, Date usuFechafinal, Date usuFechaproceso, BigDecimal usuUsuariorunt, Set civAttemptses, Set civDetalleRecUsus, Set civUsuperfils, Set civUspHistorias, Set civPerfilrecursos, Set civUsuarioCajases) {
       this.usuId = usuId;
       this.civPersonas = civPersonas;
       this.civSedes = civSedes;
       this.usuNombre = usuNombre;
       this.usuPassword = usuPassword;
       this.usuEstado = usuEstado;
       this.usuFechainicial = usuFechainicial;
       this.usuFechafinal = usuFechafinal;
       this.usuFechaproceso = usuFechaproceso;
       this.usuUsuariorunt = usuUsuariorunt;
       this.civAttemptses = civAttemptses;
       this.civDetalleRecUsus = civDetalleRecUsus;
       this.civUsuperfils = civUsuperfils;
       this.civUspHistorias = civUspHistorias;
       this.civPerfilrecursos = civPerfilrecursos;
       this.civUsuarioCajases = civUsuarioCajases;
    }
   
    public BigDecimal getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(BigDecimal usuId) {
        this.usuId = usuId;
    }
    public CivPersonas getCivPersonas() {
        return this.civPersonas;
    }
    
    public void setCivPersonas(CivPersonas civPersonas) {
        this.civPersonas = civPersonas;
    }
    public CivSedes getCivSedes() {
        return this.civSedes;
    }
    
    public void setCivSedes(CivSedes civSedes) {
        this.civSedes = civSedes;
    }
    public String getUsuNombre() {
        return this.usuNombre;
    }
    
    public void setUsuNombre(String usuNombre) {
        this.usuNombre = usuNombre;
    }
    public String getUsuPassword() {
        return this.usuPassword;
    }
    
    public void setUsuPassword(String usuPassword) {
        this.usuPassword = usuPassword;
    }
    public BigDecimal getUsuEstado() {
        return this.usuEstado;
    }
    
    public void setUsuEstado(BigDecimal usuEstado) {
        this.usuEstado = usuEstado;
    }
    public Date getUsuFechainicial() {
        return this.usuFechainicial;
    }
    
    public void setUsuFechainicial(Date usuFechainicial) {
        this.usuFechainicial = usuFechainicial;
    }
    public Date getUsuFechafinal() {
        return this.usuFechafinal;
    }
    
    public void setUsuFechafinal(Date usuFechafinal) {
        this.usuFechafinal = usuFechafinal;
    }
    public Date getUsuFechaproceso() {
        return this.usuFechaproceso;
    }
    
    public void setUsuFechaproceso(Date usuFechaproceso) {
        this.usuFechaproceso = usuFechaproceso;
    }
    public BigDecimal getUsuUsuariorunt() {
        return this.usuUsuariorunt;
    }
    
    public void setUsuUsuariorunt(BigDecimal usuUsuariorunt) {
        this.usuUsuariorunt = usuUsuariorunt;
    }
    public Set getCivAttemptses() {
        return this.civAttemptses;
    }
    
    public void setCivAttemptses(Set civAttemptses) {
        this.civAttemptses = civAttemptses;
    }
    public Set getCivDetalleRecUsus() {
        return this.civDetalleRecUsus;
    }
    
    public void setCivDetalleRecUsus(Set civDetalleRecUsus) {
        this.civDetalleRecUsus = civDetalleRecUsus;
    }
    public Set getCivUsuperfils() {
        return this.civUsuperfils;
    }
    
    public void setCivUsuperfils(Set civUsuperfils) {
        this.civUsuperfils = civUsuperfils;
    }
    public Set getCivUspHistorias() {
        return this.civUspHistorias;
    }
    
    public void setCivUspHistorias(Set civUspHistorias) {
        this.civUspHistorias = civUspHistorias;
    }
    public Set getCivPerfilrecursos() {
        return this.civPerfilrecursos;
    }
    
    public void setCivPerfilrecursos(Set civPerfilrecursos) {
        this.civPerfilrecursos = civPerfilrecursos;
    }
    public Set getCivUsuarioCajases() {
        return this.civUsuarioCajases;
    }
    
    public void setCivUsuarioCajases(Set civUsuarioCajases) {
        this.civUsuarioCajases = civUsuarioCajases;
    }




}


